class Portafolio < ActiveRecord::Base
	# COSAS QUE HACER, TENEGO QUE HACER LA VALIDACIONES PARA QUE
	# SI UN USUARIO CANCELA LA CUENTA, SE ELIMINE EL PORTAFOLIO
	# CANTIADAD DE TEXTO
	belongs_to :user
end
